version: '3.7'

services:

    # caddy:
    #     image: caddy:2.9-alpine
    #     restart: unless-stopped
    #     # cap_add:
    #     #     - NET_ADMIN
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #         - "443:443/udp"
    #     volumes:
    #         - $PWD/conf:/etc/caddy
    #         - $PWD/site:/srv
    #         - caddy_data:/data
    #         - caddy_config:/config
    #     depends_on:
    #         - apache
    nginx: 
        image: nginx:1.27-alpine
        volumes:
            - .:/var/www/html:rw
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    php:
        image: thecodingmachine/php:8.4-v4-fpm
        volumes:
            - .:/var/www/html:rw
        ports:
            - "9000:9000"
        # environment:
        #     - NGINX_HOST=foobar.com
        #     - NGINX_PORT=80

    # apache:
    #     build: 
    #         context: .
    #         dockerfile: ./docker/apache/Dockerfile
    #     ports:
    #         - "9000:80"
    #     volumes:
    #         - .:/var/www/html:rw
    #         - symfony-var:/var/www/html/var:rw
        # entrypoint: 
        #     - ./docker/demo.sh
# volumes:
    # caddy_data:
    # caddy_config:
    # symfony-var: