version: '3.7'

services:

    nginx: 
        image: nginx:1.27-alpine
        volumes:
            - .:/var/www/html:rw
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"

    php:
        image: thecodingmachine/php:8.4-v4-fpm
        volumes:
            - .:/var/www/html:rw
        ports:
            - "9000:9000"
        environment:
            - PHP_EXTENSION_PDO_PGSQL=1
            - PHP_EXTENSION_AMQP=1
    
    postgresql:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_PASSWORD=quynh121201
            - POSTGRES_USER=quynh
            - POSTGRES_DB=quynh-docker
        volumes:
            - postgres_data:/var/lib/postgresql/data:rw

    rabbitmq:
        image: bitnami/rabbitmq:latest
        environment:
            - RABBITMQ_USERNAME=quynh
            - RABBITMQ_PASSWORD=quynh121201
            - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
        ports:
            -   target: 5672
                published: 5672
                protocol: tcp
            -   target: 15672
                published: 15672
                protocol: tcp

        
volumes:
    postgres_data:


