version: '3.7'

services:

    nginx: 
        image: nginx:1.27-alpine
        volumes:
            - .:/var/www/html:rw
            - ./docker/nginx/demo-default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    php:
        image: thecodingmachine/php:8.4-v4-fpm
        volumes:
            - .:/var/www/html:rw
        ports:
            - "9000:9000"
        environment:
            - PHP_EXTENSION_PDO_PGSQL=1
    
    postgresql:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_PASSWORD=quynh121201
            - POSTGRES_USER=quynh
            - POSTGRES_DB=quynh-docker
        volumes:
            - postgres_data:/var/lib/postgresql/data:rw
        
volumes:
    postgres_data:


